# frozen_string_literal: true

# Autogenerated code. This code was generated by bin/gen-specs.rb. DO NOT EDIT.
# Edits will be lost once the generator is run again.

RSpec.describe "css-parsing-tests: one_declaration.json" do
  it "parses \"\"" do
    style = ""
    tok = TinyCSS::CSS::Tokenizer.new(style, allow_unicode_ranges: true)
    tok.tokenize
    par = TinyCSS::CSS::Parser.new(tok.tokens)
    sheet = [par.parse_declaration]
    r = TinyCSS::AST.convert(sheet)

    match_ast(r) do
      consume_error("empty")
    end
  end

  it "parses \"  /**/\\n\"" do
    style = "  /**/\n"
    tok = TinyCSS::CSS::Tokenizer.new(style, allow_unicode_ranges: true)
    tok.tokenize
    par = TinyCSS::CSS::Parser.new(tok.tokens)
    sheet = [par.parse_declaration]
    r = TinyCSS::AST.convert(sheet)

    match_ast(r) do
      consume_error("empty")
    end
  end

  it "parses \" ;\"" do
    style = " ;"
    tok = TinyCSS::CSS::Tokenizer.new(style, allow_unicode_ranges: true)
    tok.tokenize
    par = TinyCSS::CSS::Parser.new(tok.tokens)
    sheet = [par.parse_declaration]
    r = TinyCSS::AST.convert(sheet)

    match_ast(r) do
      consume_error("invalid")
    end
  end

  it "parses \"foo\"" do
    style = "foo"
    tok = TinyCSS::CSS::Tokenizer.new(style, allow_unicode_ranges: true)
    tok.tokenize
    par = TinyCSS::CSS::Parser.new(tok.tokens)
    sheet = [par.parse_declaration]
    r = TinyCSS::AST.convert(sheet)

    match_ast(r) do
      consume_error("invalid")
    end
  end

  it "parses \"@foo:\"" do
    style = "@foo:"
    tok = TinyCSS::CSS::Tokenizer.new(style, allow_unicode_ranges: true)
    tok.tokenize
    par = TinyCSS::CSS::Parser.new(tok.tokens)
    sheet = [par.parse_declaration]
    r = TinyCSS::AST.convert(sheet)

    match_ast(r) do
      consume_error("invalid")
    end
  end

  it "parses \"#foo:\"" do
    style = "#foo:"
    tok = TinyCSS::CSS::Tokenizer.new(style, allow_unicode_ranges: true)
    tok.tokenize
    par = TinyCSS::CSS::Parser.new(tok.tokens)
    sheet = [par.parse_declaration]
    r = TinyCSS::AST.convert(sheet)

    match_ast(r) do
      consume_error("invalid")
    end
  end

  it "parses \".foo:\"" do
    style = ".foo:"
    tok = TinyCSS::CSS::Tokenizer.new(style, allow_unicode_ranges: true)
    tok.tokenize
    par = TinyCSS::CSS::Parser.new(tok.tokens)
    sheet = [par.parse_declaration]
    r = TinyCSS::AST.convert(sheet)

    match_ast(r) do
      consume_error("invalid")
    end
  end

  it "parses \"foo*:\"" do
    style = "foo*:"
    tok = TinyCSS::CSS::Tokenizer.new(style, allow_unicode_ranges: true)
    tok.tokenize
    par = TinyCSS::CSS::Parser.new(tok.tokens)
    sheet = [par.parse_declaration]
    r = TinyCSS::AST.convert(sheet)

    match_ast(r) do
      consume_error("invalid")
    end
  end

  it "parses \"foo.. 9000\"" do
    style = "foo.. 9000"
    tok = TinyCSS::CSS::Tokenizer.new(style, allow_unicode_ranges: true)
    tok.tokenize
    par = TinyCSS::CSS::Parser.new(tok.tokens)
    sheet = [par.parse_declaration]
    r = TinyCSS::AST.convert(sheet)

    match_ast(r) do
      consume_error("invalid")
    end
  end

  it "parses \"foo:\"" do
    style = "foo:"
    tok = TinyCSS::CSS::Tokenizer.new(style, allow_unicode_ranges: true)
    tok.tokenize
    par = TinyCSS::CSS::Parser.new(tok.tokens)
    sheet = [par.parse_declaration]
    r = TinyCSS::AST.convert(sheet)

    match_ast(r) do
      decl("foo", important: false) do
        empty!
      end
    end
  end

  it "parses \"foo :\"" do
    style = "foo :"
    tok = TinyCSS::CSS::Tokenizer.new(style, allow_unicode_ranges: true)
    tok.tokenize
    par = TinyCSS::CSS::Parser.new(tok.tokens)
    sheet = [par.parse_declaration]
    r = TinyCSS::AST.convert(sheet)

    match_ast(r) do
      decl("foo", important: false) do
        empty!
      end
    end
  end

  it "parses \"\\n/**/ foo: \"" do
    style = "\n/**/ foo: "
    tok = TinyCSS::CSS::Tokenizer.new(style, allow_unicode_ranges: true)
    tok.tokenize
    par = TinyCSS::CSS::Parser.new(tok.tokens)
    sheet = [par.parse_declaration]
    r = TinyCSS::AST.convert(sheet)

    match_ast(r) do
      decl("foo", important: false) do
        empty!
      end
    end
  end

  it "parses \"foo:;\"" do
    style = "foo:;"
    tok = TinyCSS::CSS::Tokenizer.new(style, allow_unicode_ranges: true)
    tok.tokenize
    par = TinyCSS::CSS::Parser.new(tok.tokens)
    sheet = [par.parse_declaration]
    r = TinyCSS::AST.convert(sheet)

    match_ast(r) do
      decl("foo", important: false) do
        empty!
      end
    end
  end

  it "parses \" /**/ foo /**/ :\"" do
    style = " /**/ foo /**/ :"
    tok = TinyCSS::CSS::Tokenizer.new(style, allow_unicode_ranges: true)
    tok.tokenize
    par = TinyCSS::CSS::Parser.new(tok.tokens)
    sheet = [par.parse_declaration]
    r = TinyCSS::AST.convert(sheet)

    match_ast(r) do
      decl("foo", important: false) do
        empty!
      end
    end
  end

  it "parses \"foo:;bar:;\"" do
    style = "foo:;bar:;"
    tok = TinyCSS::CSS::Tokenizer.new(style, allow_unicode_ranges: true)
    tok.tokenize
    par = TinyCSS::CSS::Parser.new(tok.tokens)
    sheet = [par.parse_declaration]
    r = TinyCSS::AST.convert(sheet)

    match_ast(r) do
      decl("foo", important: false) do
        empty!
      end
    end
  end

  it "parses \"foo: 9000  !Important\"" do
    style = "foo: 9000  !Important"
    tok = TinyCSS::CSS::Tokenizer.new(style, allow_unicode_ranges: true)
    tok.tokenize
    par = TinyCSS::CSS::Parser.new(tok.tokens)
    sheet = [par.parse_declaration]
    r = TinyCSS::AST.convert(sheet)

    match_ast(r) do
      decl("foo", important: true) do
        number 9000, :integer
      end
    end
  end

  it "parses \"foo: 9000  ! /**/\\t IMPORTant /**/\\f\"" do
    style = "foo: 9000  ! /**/\t IMPORTant /**/\f"
    tok = TinyCSS::CSS::Tokenizer.new(style, allow_unicode_ranges: true)
    tok.tokenize
    par = TinyCSS::CSS::Parser.new(tok.tokens)
    sheet = [par.parse_declaration]
    r = TinyCSS::AST.convert(sheet)

    match_ast(r) do
      decl("foo", important: true) do
        number 9000, :integer
      end
    end
  end

  it "parses \"foo: 9000  /* Dotted capital I */!\\u0130mportant\"" do
    style = "foo: 9000  /* Dotted capital I */!\u0130mportant"
    tok = TinyCSS::CSS::Tokenizer.new(style, allow_unicode_ranges: true)
    tok.tokenize
    par = TinyCSS::CSS::Parser.new(tok.tokens)
    sheet = [par.parse_declaration]
    r = TinyCSS::AST.convert(sheet)

    match_ast(r) do
      decl("foo", important: false) do
        number 9000, :integer
        string " "
        string "!"
        ident "İmportant"
      end
    end
  end

  it "parses \"foo: 9000  !important!\"" do
    style = "foo: 9000  !important!"
    tok = TinyCSS::CSS::Tokenizer.new(style, allow_unicode_ranges: true)
    tok.tokenize
    par = TinyCSS::CSS::Parser.new(tok.tokens)
    sheet = [par.parse_declaration]
    r = TinyCSS::AST.convert(sheet)

    match_ast(r) do
      decl("foo", important: false) do
        number 9000, :integer
        string " "
        string "!"
        ident "important"
        string "!"
      end
    end
  end

  it "parses \"foo: 9000  important\"" do
    style = "foo: 9000  important"
    tok = TinyCSS::CSS::Tokenizer.new(style, allow_unicode_ranges: true)
    tok.tokenize
    par = TinyCSS::CSS::Parser.new(tok.tokens)
    sheet = [par.parse_declaration]
    r = TinyCSS::AST.convert(sheet)

    match_ast(r) do
      decl("foo", important: false) do
        number 9000, :integer
        string " "
        ident "important"
      end
    end
  end

  it "parses \"foo:important\"" do
    style = "foo:important"
    tok = TinyCSS::CSS::Tokenizer.new(style, allow_unicode_ranges: true)
    tok.tokenize
    par = TinyCSS::CSS::Parser.new(tok.tokens)
    sheet = [par.parse_declaration]
    r = TinyCSS::AST.convert(sheet)

    match_ast(r) do
      decl("foo", important: false) do
        ident "important"
      end
    end
  end

end